// Al-Fātiḥah and the last 20 surahs (95–114).
//
// Each ayah has: Arabic (standard script with full vowels), transliteration
// with tajweed markup, and a plain English rendering of the meaning.
//
// Transliteration follows the reading of Ḥafṣ ʿan ʿĀṣim, stopping at the end
// of each ayah (and at the pause marks inside long ayat). Markup codes are
// defined in lib/ui/tajweed.dart. The English is an approximate rendering of
// the meaning, not a translation to rely on for rulings.
//
// Please report any error you find; check against a printed muṣḥaf and,
// ideally, a qualified teacher.

class Ayah {
  final String ar;
  final String tr;
  final String en;
  const Ayah(this.ar, this.tr, this.en);
}

class Surah {
  final int number;
  final String name;
  final String arabicName;
  final String meaning;
  final List<Ayah> ayat;
  const Surah(this.number, this.name, this.arabicName, this.meaning, this.ayat);

  /// In Al-Fātiḥah the basmalah is the first ayah; elsewhere it is recited
  /// before the surah but not numbered.
  bool get basmalahIsAyah => number == 1;
}

const Ayah kBasmalah = Ayah(
  'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
  'bismil-lāhir-raḥmānir-raḥ{Ma:ī}m',
  "In the name of Allah, the Most Compassionate, the Most Merciful.",
);

const List<Surah> kSurahs = [
  Surah(1, 'Al-Fātiḥah', 'الفاتحة', 'The Opening', [
    kBasmalah,
    Ayah('الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
        'al-ḥamdu lillāhi rabbil-ʿālam{Ma:ī}n',
        "All praise belongs to Allah, Lord of all the worlds,"),
    Ayah('الرَّحْمَٰنِ الرَّحِيمِ', 'ar-raḥmānir-raḥ{Ma:ī}m',
        "the Most Compassionate, the Most Merciful,"),
    Ayah('مَالِكِ يَوْمِ الدِّينِ', 'māliki yawmid-d{Ma:ī}n',
        "Master of the Day of Judgement."),
    Ayah('إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        'iyyāka naʿ{Q:b}udu wa iyyāka nastaʿ{Ma:ī}n',
        "You alone we worship, and You alone we ask for help."),
    Ayah('اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ', 'ihdinaṣ-ṣirāṭal-mustaq{Ma:ī}m',
        "Guide us along the straight path,"),
    Ayah(
        'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
        'ṣirāṭal-ladhīna anʿamta ʿalayhim ghayril-maghḍūbi ʿalayhim wa laḍ-ḍ{Ml:ā}ll{Ma:ī}n',
        "the path of those You have blessed, not of those who have earned Your anger, nor of those who have gone astray."),
  ]),
  Surah(95, 'At-Tīn', 'التين', 'The Fig', [
    Ayah('وَالتِّينِ وَالزَّيْتُونِ', 'wat-tīni waz-zayt{Ma:ū}n',
        "By the fig and the olive,"),
    Ayah('وَطُورِ سِينِينَ', 'wa ṭūri sīn{Ma:ī}n', "and by Mount Sinai,"),
    Ayah('وَهَٰذَا الْبَلَدِ الْأَمِينِ', 'wa hādhal-baladil-am{Ma:ī}n',
        "and by this secure city:"),
    Ayah('لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ',
        'laqa{Q:d} khala{Q:q}nal-i{I:n}sāna f{Mj:ī} aḥsani ta{Q:q}w{Ma:ī}m',
        "We created humankind in the finest form,"),
    Ayah('ثُمَّ رَدَدْنَاهُ أَسْفَلَ سَافِلِينَ',
        'thu{G:mm}a rada{Q:d}nāhu asfala sāfil{Ma:ī}n',
        "then We reduced them to the lowest of the low,"),
    Ayah(
        'إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَلَهُمْ أَجْرٌ غَيْرُ مَمْنُونٍ',
        'illal-ladhīna āmanū wa ʿamiluṣ-ṣāliḥāti falahum ajrun ghayru mamn{Ma:ū}n',
        "except those who believe and do good deeds: theirs is a reward that never ends."),
    Ayah('فَمَا يُكَذِّبُكَ بَعْدُ بِالدِّينِ',
        'famā yukadhdhibuka baʿdu bid-d{Ma:ī}n',
        "So what, after this, makes you deny the Judgement?"),
    Ayah('أَلَيْسَ اللَّهُ بِأَحْكَمِ الْحَاكِمِينَ',
        'alaysal-lāhu bi-aḥkamil-ḥākim{Ma:ī}n',
        "Is Allah not the most just of judges?"),
  ]),
  Surah(96, 'Al-ʿAlaq', 'العلق', 'The Clinging Clot', [
    Ayah('اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',
        'i{Q:q}raʾ bismi rabbikal-ladhī khala{Q:q}',
        "Read in the name of your Lord who created,"),
    Ayah('خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ', 'khalaqal-i{I:n}sāna min ʿala{Q:q}',
        "created humankind from a clinging clot."),
    Ayah('اقْرَأْ وَرَبُّكَ الْأَكْرَمُ', 'i{Q:q}raʾ wa rabbukal-akram',
        "Read, for your Lord is the Most Generous,"),
    Ayah('الَّذِي عَلَّمَ بِالْقَلَمِ', 'alladhī ʿallama bil-qalam',
        "who taught by the pen,"),
    Ayah('عَلَّمَ الْإِنسَانَ مَا لَمْ يَعْلَمْ',
        'ʿallamal-i{I:n}sāna mā lam yaʿlam',
        "taught humankind what it did not know."),
    Ayah('كَلَّا إِنَّ الْإِنسَانَ لَيَطْغَىٰ',
        'kall{Mj:ā} i{G:nn}al-i{I:n}sāna laya{Q:ṭ}ghā',
        "No indeed, humankind oversteps all bounds"),
    Ayah('أَن رَّآهُ اسْتَغْنَىٰ', 'a{Dn:r-r}aʾāhus-taghnā',
        "when they think themselves self-sufficient."),
    Ayah('إِنَّ إِلَىٰ رَبِّكَ الرُّجْعَىٰ', 'i{G:nn}a ilā rabbikar-ru{Q:j}ʿā',
        "Truly, to your Lord is the return."),
    Ayah('أَرَأَيْتَ الَّذِي يَنْهَىٰ', 'araʾaytal-ladhī yanhā',
        "Have you seen the one who forbids"),
    Ayah('عَبْدًا إِذَا صَلَّىٰ', 'ʿa{Q:b}dan idhā ṣallā',
        "a servant from praying?"),
    Ayah('أَرَأَيْتَ إِن كَانَ عَلَى الْهُدَىٰ',
        'araʾayta i{I:n} kāna ʿalal-hudā',
        "Have you considered if that servant is rightly guided,"),
    Ayah('أَوْ أَمَرَ بِالتَّقْوَىٰ', 'aw amara bit-ta{Q:q}wā',
        "or urges mindfulness of God?"),
    Ayah('أَرَأَيْتَ إِن كَذَّبَ وَتَوَلَّىٰ',
        'araʾayta i{I:n} kadhdhaba wa tawallā',
        "Have you considered if the other denies and turns away?"),
    Ayah('أَلَمْ يَعْلَم بِأَنَّ اللَّهَ يَرَىٰ',
        'alam yaʿla{Is:m} bi-a{G:nn}al-lāha yarā',
        "Does he not know that Allah sees?"),
    Ayah('كَلَّا لَئِن لَّمْ يَنتَهِ لَنَسْفَعًا بِالنَّاصِيَةِ',
        'kallā laʾi{Dn:l-l}am ya{I:n}tahi lanasfaʿa{B:m} bi{G:n-n}āṣiyah',
        "No indeed! If he does not stop, We will seize him by the forelock,"),
    Ayah('نَاصِيَةٍ كَاذِبَةٍ خَاطِئَةٍ', 'nāṣiyati{I:n} kādhibatin khāṭiʾah',
        "a lying, sinful forelock."),
    Ayah('فَلْيَدْعُ نَادِيَهُ', 'falya{Q:d}ʿu nādiyah',
        "So let him call his gathering;"),
    Ayah('سَنَدْعُ الزَّبَانِيَةَ', 'sana{Q:d}ʿuz-zabāniyah',
        "We will call the guards of Hell."),
    Ayah('كَلَّا لَا تُطِعْهُ وَاسْجُدْ وَاقْتَرِب',
        'kallā lā tuṭiʿhu wasju{Q:d} wa{Q:q}tari{Q:b}',
        "No indeed! Do not obey him. Prostrate and draw near. (A place of prostration.)"),
  ]),
  Surah(97, 'Al-Qadr', 'القدر', 'The Night of Decree', [
    Ayah('إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ',
        'i{G:nn}{Mj:ā} a{I:n}zalnāhu fī laylatil-qa{Q:d}r',
        "We sent it down on the Night of Decree."),
    Ayah('وَمَا أَدْرَاكَ مَا لَيْلَةُ الْقَدْرِ',
        'wa m{Mj:ā} a{Q:d}rāka mā laylatul-qa{Q:d}r',
        "And what will make you understand what the Night of Decree is?"),
    Ayah('لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ',
        'laylatul-qa{Q:d}ri khayru{Dg:m-m}in alfi shahr',
        "The Night of Decree is better than a thousand months."),
    Ayah('تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ',
        'tanazzalul-mal{Mw:ā}ʾikatu war-rūḥu fīhā bi-idhni rabbihi{Dg:m-m}i{I:n} kulli amr',
        "In it the angels and the Spirit descend, by their Lord’s permission, with every decree."),
    Ayah('سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ',
        'salāmun hiya ḥattā ma{Q:ṭ}laʿil-fa{Q:j}r',
        "Peace it is, until the break of dawn."),
  ]),
  Surah(98, 'Al-Bayyinah', 'البينة', 'The Clear Proof', [
    Ayah(
        'لَمْ يَكُنِ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَالْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ الْبَيِّنَةُ',
        'lam yakunil-ladhīna kafarū min ahlil-kitābi wal-mushrikīna mu{I:n}fakkīna ḥattā taʾtiyahumul-bayyinah',
        "Those who disbelieved among the People of the Book and the idolaters were not going to let go until the clear proof came to them:"),
    Ayah('رَسُولٌ مِّنَ اللَّهِ يَتْلُو صُحُفًا مُّطَهَّرَةً',
        'rasūlu{Dg:m-m}inal-lāhi yatlū ṣuḥufa{Dg:m-m}uṭahharah',
        "a messenger from Allah, reciting purified scriptures"),
    Ayah('فِيهَا كُتُبٌ قَيِّمَةٌ', 'fīhā kutubu{I:n} qayyimah',
        "containing upright writings."),
    Ayah(
        'وَمَا تَفَرَّقَ الَّذِينَ أُوتُوا الْكِتَابَ إِلَّا مِن بَعْدِ مَا جَاءَتْهُمُ الْبَيِّنَةُ',
        'wa mā tafarraqal-ladhīna ūtul-kitāba illā mi{B:m} baʿdi mā j{Mw:ā}ʾathumul-bayyinah',
        "Those who were given the Book did not divide until after the clear proof had come to them."),
    Ayah(
        'وَمَا أُمِرُوا إِلَّا لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ حُنَفَاءَ وَيُقِيمُوا الصَّلَاةَ وَيُؤْتُوا الزَّكَاةَ ۚ وَذَٰلِكَ دِينُ الْقَيِّمَةِ',
        'wa m{Mj:ā} umir{Mj:ū} illā liyaʿ{Q:b}udul-lāha mukhliṣīna lahud-dīna ḥunaf{Mw:ā}ʾa wa yuqīmuṣ-ṣalāta wa yuʾtuz-zakāh. wa dhālika dīnul-qayyimah',
        "Yet they were commanded only to worship Allah, devoting their faith sincerely to Him and turning away from falsehood, to establish prayer and to give zakah. That is the upright religion."),
    Ayah(
        'إِنَّ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَالْمُشْرِكِينَ فِي نَارِ جَهَنَّمَ خَالِدِينَ فِيهَا ۚ أُولَٰئِكَ هُمْ شَرُّ الْبَرِيَّةِ',
        'i{G:nn}al-ladhīna kafarū min ahlil-kitābi wal-mushrikīna fī nāri jaha{G:nn}ama khālidīna fīhā. ul{Mw:ā}ʾika hum sharrul-bariyyah',
        "Those who disbelieved among the People of the Book and the idolaters will be in the fire of Hell, remaining there. They are the worst of creation."),
    Ayah(
        'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أُولَٰئِكَ هُمْ خَيْرُ الْبَرِيَّةِ',
        'i{G:nn}al-ladhīna āmanū wa ʿamiluṣ-ṣāliḥāti ul{Mw:ā}ʾika hum khayrul-bariyyah',
        "Those who believe and do good deeds are the best of creation."),
    Ayah(
        'جَزَاؤُهُمْ عِندَ رَبِّهِمْ جَنَّاتُ عَدْنٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ خَالِدِينَ فِيهَا أَبَدًا ۖ رَّضِيَ اللَّهُ عَنْهُمْ وَرَضُوا عَنْهُ ۚ ذَٰلِكَ لِمَنْ خَشِيَ رَبَّهُ',
        'jaz{Mw:ā}ʾuhum ʿi{I:n}da rabbihim ja{G:nn}ātu ʿa{Q:d}ni{I:n} ta{Q:j}rī mi{I:n} taḥtihal-anhāru khālidīna fīh{Mj:ā} abadā. raḍiyal-lāhu ʿanhum wa raḍū ʿanh. dhālika liman khashiya rabbah',
        "Their reward with their Lord is gardens of lasting residence with rivers flowing beneath them, where they will remain forever. Allah is pleased with them and they are pleased with Him. That is for whoever stands in awe of their Lord."),
  ]),
  Surah(99, 'Az-Zalzalah', 'الزلزلة', 'The Earthquake', [
    Ayah('إِذَا زُلْزِلَتِ الْأَرْضُ زِلْزَالَهَا',
        'idhā zulzilatil-arḍu zilzālahā',
        "When the earth is shaken with its final shaking,"),
    Ayah('وَأَخْرَجَتِ الْأَرْضُ أَثْقَالَهَا',
        'wa akhrajatil-arḍu ath{Q:q}ālahā',
        "and the earth brings out its burdens,"),
    Ayah('وَقَالَ الْإِنسَانُ مَا لَهَا', 'wa qālal-i{I:n}sānu mā lahā',
        "and people cry, “What is happening to it?”"),
    Ayah('يَوْمَئِذٍ تُحَدِّثُ أَخْبَارَهَا',
        'yawmaʾidhi{I:n} tuḥaddithu akhbārahā',
        "On that Day it will tell its news,"),
    Ayah('بِأَنَّ رَبَّكَ أَوْحَىٰ لَهَا', 'bi-a{G:nn}a rabbaka awḥā lahā',
        "because your Lord will have inspired it."),
    Ayah('يَوْمَئِذٍ يَصْدُرُ النَّاسُ أَشْتَاتًا لِّيُرَوْا أَعْمَالَهُمْ',
        'yawmaʾidhi{Dg:y-y}aṣduru{G:n-n}āsu ashtāta{Dn:l-l}iyuraw aʿmālahum',
        "On that Day people will come forward in scattered groups to be shown their deeds."),
    Ayah('فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ',
        'fama{Dg:y-y}aʿmal mith{Q:q}āla dharratin khayra{Dg:y-y}arah',
        "Whoever does an atom’s weight of good will see it,"),
    Ayah('وَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ',
        'wa ma{Dg:y-y}aʿmal mith{Q:q}āla dharrati{I:n} sharra{Dg:y-y}arah',
        "and whoever does an atom’s weight of evil will see it."),
  ]),
  Surah(100, 'Al-ʿĀdiyāt', 'العاديات', 'The Charging Horses', [
    Ayah('وَالْعَادِيَاتِ ضَبْحًا', 'wal-ʿādiyāti ḍa{Q:b}ḥā',
        "By the charging horses, panting,"),
    Ayah('فَالْمُورِيَاتِ قَدْحًا', 'fal-mūriyāti qa{Q:d}ḥā',
        "striking sparks with their hooves,"),
    Ayah('فَالْمُغِيرَاتِ صُبْحًا', 'fal-mughīrāti ṣu{Q:b}ḥā',
        "raiding at dawn,"),
    Ayah('فَأَثَرْنَ بِهِ نَقْعًا', 'fa-atharna bihī na{Q:q}ʿā',
        "raising clouds of dust,"),
    Ayah('فَوَسَطْنَ بِهِ جَمْعًا', 'fawasa{Q:ṭ}na bihī jamʿā',
        "and plunging into the midst of a host:"),
    Ayah('إِنَّ الْإِنسَانَ لِرَبِّهِ لَكَنُودٌ',
        'i{G:nn}al-i{I:n}sāna lirabbihī lakan{Ma:ū}{Q:d}',
        "truly, humankind is ungrateful to their Lord,"),
    Ayah('وَإِنَّهُ عَلَىٰ ذَٰلِكَ لَشَهِيدٌ',
        'wa i{G:nn}ahū ʿalā dhālika lashah{Ma:ī}{Q:d}',
        "and they themselves bear witness to it,"),
    Ayah('وَإِنَّهُ لِحُبِّ الْخَيْرِ لَشَدِيدٌ',
        'wa i{G:nn}ahū liḥubbil-khayri lashad{Ma:ī}{Q:d}',
        "and they are fierce in their love of wealth."),
    Ayah('أَفَلَا يَعْلَمُ إِذَا بُعْثِرَ مَا فِي الْقُبُورِ',
        'afalā yaʿlamu idhā buʿthira mā fil-qub{Ma:ū}r',
        "Do they not know that when what is in the graves is brought out,"),
    Ayah('وَحُصِّلَ مَا فِي الصُّدُورِ', 'wa ḥuṣṣila mā fiṣ-ṣud{Ma:ū}r',
        "and what is in the hearts is laid bare,"),
    Ayah('إِنَّ رَبَّهُم بِهِمْ يَوْمَئِذٍ لَّخَبِيرٌ',
        'i{G:nn}a rabbahu{Is:m} bihim yawmaʾidhi{Dn:l-l}akhab{Ma:ī}r',
        "on that Day their Lord will be fully aware of them?"),
  ]),
  Surah(101, 'Al-Qāriʿah', 'القارعة', 'The Striking Calamity', [
    Ayah('الْقَارِعَةُ', 'al-qāriʿah', "The Striking Calamity!"),
    Ayah('مَا الْقَارِعَةُ', 'mal-qāriʿah', "What is the Striking Calamity?"),
    Ayah('وَمَا أَدْرَاكَ مَا الْقَارِعَةُ',
        'wa m{Mj:ā} a{Q:d}rāka mal-qāriʿah',
        "And what will make you understand what the Striking Calamity is?"),
    Ayah('يَوْمَ يَكُونُ النَّاسُ كَالْفَرَاشِ الْمَبْثُوثِ',
        'yawma yakūnu{G:n-n}āsu kal-farāshil-ma{Q:b}th{Ma:ū}th',
        "It is the Day people will be like scattered moths,"),
    Ayah('وَتَكُونُ الْجِبَالُ كَالْعِهْنِ الْمَنفُوشِ',
        'wa takūnul-jibālu kal-ʿihnil-ma{I:n}f{Ma:ū}sh',
        "and the mountains like tufts of carded wool."),
    Ayah('فَأَمَّا مَن ثَقُلَتْ مَوَازِينُهُ',
        'fa-a{G:mm}ā ma{I:n} thaqulat mawāzīnuh',
        "As for the one whose scales are heavy,"),
    Ayah('فَهُوَ فِي عِيشَةٍ رَّاضِيَةٍ', 'fahuwa fī ʿīshati{Dn:r-r}āḍiyah',
        "they will have a life of contentment."),
    Ayah('وَأَمَّا مَنْ خَفَّتْ مَوَازِينُهُ',
        'wa a{G:mm}ā man khaffat mawāzīnuh',
        "But as for the one whose scales are light,"),
    Ayah('فَأُمُّهُ هَاوِيَةٌ', 'fa-u{G:mm}uhū hāwiyah',
        "their home will be the Abyss."),
    Ayah('وَمَا أَدْرَاكَ مَا هِيَهْ', 'wa m{Mj:ā} a{Q:d}rāka mā hiyah',
        "And what will make you understand what that is?"),
    Ayah('نَارٌ حَامِيَةٌ', 'nārun ḥāmiyah', "A blazing Fire."),
  ]),
  Surah(102, 'At-Takāthur', 'التكاثر', 'Competing for More', [
    Ayah('أَلْهَاكُمُ التَّكَاثُرُ', 'alhākumut-takāthur',
        "Competing for more distracts you"),
    Ayah('حَتَّىٰ زُرْتُمُ الْمَقَابِرَ', 'ḥattā zurtumul-maqābir',
        "until you visit the graves."),
    Ayah('كَلَّا سَوْفَ تَعْلَمُونَ', 'kallā sawfa taʿlam{Ma:ū}n',
        "No indeed! You will come to know."),
    Ayah('ثُمَّ كَلَّا سَوْفَ تَعْلَمُونَ',
        'thu{G:mm}a kallā sawfa taʿlam{Ma:ū}n',
        "Again, no indeed! You will come to know."),
    Ayah('كَلَّا لَوْ تَعْلَمُونَ عِلْمَ الْيَقِينِ',
        'kallā law taʿlamūna ʿilmal-yaq{Ma:ī}n',
        "No indeed! If only you knew with certain knowledge,"),
    Ayah('لَتَرَوُنَّ الْجَحِيمَ', 'latarawu{G:nn}al-jaḥ{Ma:ī}m',
        "you would surely see the Blazing Fire."),
    Ayah('ثُمَّ لَتَرَوُنَّهَا عَيْنَ الْيَقِينِ',
        'thu{G:mm}a latarawu{G:nn}ahā ʿaynal-yaq{Ma:ī}n',
        "Then you will surely see it with the eye of certainty."),
    Ayah('ثُمَّ لَتُسْأَلُنَّ يَوْمَئِذٍ عَنِ النَّعِيمِ',
        'thu{G:mm}a latusʾalu{G:nn}a yawmaʾidhin ʿani{G:n-n}aʿ{Ma:ī}m',
        "Then on that Day you will surely be asked about the pleasures you enjoyed."),
  ]),
  Surah(103, 'Al-ʿAṣr', 'العصر', 'Time', [
    Ayah('وَالْعَصْرِ', 'wal-ʿaṣr', "By time,"),
    Ayah('إِنَّ الْإِنسَانَ لَفِي خُسْرٍ', 'i{G:nn}al-i{I:n}sāna lafī khusr',
        "humankind is surely in loss,"),
    Ayah(
        'إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',
        'illal-ladhīna āmanū wa ʿamiluṣ-ṣāliḥāti wa tawāṣaw bil-ḥaqqi wa tawāṣaw biṣ-ṣa{Q:b}r',
        "except those who believe, do good deeds, urge one another to the truth, and urge one another to patience."),
  ]),
  Surah(104, 'Al-Humazah', 'الهمزة', 'The Slanderer', [
    Ayah('وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ',
        'waylu{Dn:l-l}ikulli humazati{Dn:l-l}umazah',
        "Woe to every slanderer and fault-finder,"),
    Ayah('الَّذِي جَمَعَ مَالًا وَعَدَّدَهُ',
        'alladhī jamaʿa māla{Dg:w-w}a ʿaddadah',
        "who gathers wealth and counts it again and again,"),
    Ayah('يَحْسَبُ أَنَّ مَالَهُ أَخْلَدَهُ',
        'yaḥsabu a{G:nn}a mālah{Mj:ū} akhladah',
        "thinking their wealth will make them last forever."),
    Ayah('كَلَّا ۖ لَيُنبَذَنَّ فِي الْحُطَمَةِ',
        'kallā. layu{B:m}badha{G:nn}a fil-ḥuṭamah',
        "No indeed! They will be flung into the Crusher."),
    Ayah('وَمَا أَدْرَاكَ مَا الْحُطَمَةُ',
        'wa m{Mj:ā} a{Q:d}rāka mal-ḥuṭamah',
        "And what will make you understand what the Crusher is?"),
    Ayah('نَارُ اللَّهِ الْمُوقَدَةُ', 'nārul-lāhil-mūqadah',
        "It is the kindled fire of Allah,"),
    Ayah('الَّتِي تَطَّلِعُ عَلَى الْأَفْئِدَةِ',
        'allatī taṭṭaliʿu ʿalal-afʾidah',
        "which rises over the hearts."),
    Ayah('إِنَّهَا عَلَيْهِم مُّؤْصَدَةٌ', 'i{G:nn}ahā ʿalayhi{Dg:m-m}uʾṣadah',
        "It will close in over them"),
    Ayah('فِي عَمَدٍ مُّمَدَّدَةٍ', 'fī ʿamadi{Dg:m-m}umaddadah',
        "in towering columns."),
  ]),
  Surah(105, 'Al-Fīl', 'الفيل', 'The Elephant', [
    Ayah('أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ',
        'alam tara kayfa faʿala rabbuka bi-aṣḥābil-f{Ma:ī}l',
        "Have you not seen how your Lord dealt with the army of the elephant?"),
    Ayah('أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ',
        'alam ya{Q:j}ʿal kaydahum fī taḍl{Ma:ī}l',
        "Did He not make their plan go astray?"),
    Ayah('وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ',
        'wa arsala ʿalayhim ṭayran abāb{Ma:ī}l',
        "He sent against them flocks of birds,"),
    Ayah('تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ',
        'tarmīhi{Is:m} biḥijārati{Dg:m-m}i{I:n} sijj{Ma:ī}l',
        "pelting them with stones of baked clay,"),
    Ayah('فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ',
        'fajaʿalahum kaʿaṣfi{Dg:m-m}aʾk{Ma:ū}l',
        "and left them like chewed-up straw."),
  ]),
  Surah(106, 'Quraysh', 'قريش', 'Quraysh', [
    Ayah('لِإِيلَافِ قُرَيْشٍ', 'li-īlāfi qur{Mn:ay}sh',
        "For the security of Quraysh,"),
    Ayah('إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ',
        'īlāfihim riḥlatash-shit{Mw:ā}ʾi waṣ-ṣ{Mn:ay}f',
        "their security in the journeys of winter and summer,"),
    Ayah('فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ',
        'falyaʿ{Q:b}udū rabba hādhal-b{Mn:ay}t',
        "let them worship the Lord of this House,"),
    Ayah('الَّذِي أَطْعَمَهُم مِّن جُوعٍ وَآمَنَهُم مِّنْ خَوْفٍ',
        'alladhī a{Q:ṭ}ʿamahu{Dg:m-m}i{I:n} jūʿi{Dg:w-w}a āmanahu{Dg:m-m}in kh{Mn:aw}f',
        "who fed them in hunger and made them safe from fear."),
  ]),
  Surah(107, 'Al-Māʿūn', 'الماعون', 'Small Kindnesses', [
    Ayah('أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ',
        'araʾaytal-ladhī yukadhdhibu bid-d{Ma:ī}n',
        "Have you seen the one who denies the Judgement?"),
    Ayah('فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ',
        'fadhālikal-ladhī yaduʿʿul-yat{Ma:ī}m',
        "That is the one who pushes away the orphan"),
    Ayah('وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ',
        'wa lā yaḥuḍḍu ʿalā ṭaʿāmil-misk{Ma:ī}n',
        "and does not encourage feeding the poor."),
    Ayah('فَوَيْلٌ لِّلْمُصَلِّينَ', 'fawaylu{Dn:l-l}il-muṣall{Ma:ī}n',
        "So woe to those who pray"),
    Ayah('الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ',
        'alladhīna hum ʿa{I:n} ṣalātihim sāh{Ma:ū}n',
        "but are careless of their prayer,"),
    Ayah('الَّذِينَ هُمْ يُرَاءُونَ', 'alladhīna hum yur{Mw:ā}ʾ{Ma:ū}n',
        "those who only want to be seen,"),
    Ayah('وَيَمْنَعُونَ الْمَاعُونَ', 'wa yamnaʿūnal-māʿ{Ma:ū}n',
        "and who hold back even small kindnesses."),
  ]),
  Surah(108, 'Al-Kawthar', 'الكوثر', 'Abundance', [
    Ayah('إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ', 'i{G:nn}{Mj:ā} aʿṭaynākal-kawthar',
        "We have given you abundance,"),
    Ayah('فَصَلِّ لِرَبِّكَ وَانْحَرْ', 'faṣalli lirabbika wanḥar',
        "so pray to your Lord and sacrifice."),
    Ayah('إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ', 'i{G:nn}a shāniʾaka huwal-a{Q:b}tar',
        "It is the one who hates you who is cut off."),
  ]),
  Surah(109, 'Al-Kāfirūn', 'الكافرون', 'The Disbelievers', [
    Ayah('قُلْ يَا أَيُّهَا الْكَافِرُونَ', 'qul y{Mj:ā} ayyuhal-kāfir{Ma:ū}n',
        "Say, “Disbelievers:"),
    Ayah('لَا أَعْبُدُ مَا تَعْبُدُونَ',
        'l{Mj:ā} aʿ{Q:b}udu mā taʿ{Q:b}ud{Ma:ū}n',
        "I do not worship what you worship,"),
    Ayah('وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ',
        'wa l{Mj:ā} a{I:n}tum ʿābidūna m{Mj:ā} aʿ{Q:b}u{Q:d}',
        "and you do not worship what I worship,"),
    Ayah('وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ',
        'wa l{Mj:ā} ana ʿābidu{Dg:m-m}ā ʿaba{Dx:tt}um',
        "and I will never worship what you worship,"),
    Ayah('وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ',
        'wa l{Mj:ā} a{I:n}tum ʿābidūna m{Mj:ā} aʿ{Q:b}u{Q:d}',
        "and you will never worship what I worship."),
    Ayah('لَكُمْ دِينُكُمْ وَلِيَ دِينِ', 'lakum dīnukum wa liya d{Ma:ī}n',
        "You have your religion and I have mine.”"),
  ]),
  Surah(110, 'An-Naṣr', 'النصر', 'Help', [
    Ayah('إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ',
        'idhā j{Mw:ā}ʾa naṣrul-lāhi wal-fatḥ',
        "When Allah’s help comes, and the victory,"),
    Ayah('وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا',
        'wa raʾayta{G:n-n}āsa ya{Q:d}khulūna fī dīnil-lāhi afwājā',
        "and you see people entering Allah’s religion in crowds,"),
    Ayah('فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا',
        'fasabbiḥ biḥamdi rabbika wastaghfirh. i{G:nn}ahū kāna tawwābā',
        "then glorify your Lord with praise and ask His forgiveness. He is always ready to accept repentance."),
  ]),
  Surah(111, 'Al-Masad', 'المسد', 'Palm Fibre', [
    Ayah('تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ',
        'tabbat yad{Mj:ā} abī lahabi{Dg:w-w}a ta{Q:bb}',
        "May the hands of Abu Lahab perish, and he has perished."),
    Ayah('مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ',
        'm{Mj:ā} aghnā ʿanhu māluhū wa mā kasa{Q:b}',
        "His wealth and what he earned will not help him."),
    Ayah('سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ', 'sayaṣlā nāra{I:n} dhāta laha{Q:b}',
        "He will burn in a blazing Fire,"),
    Ayah('وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ',
        'wamraʾatuhū ḥa{G:mm}ālatal-ḥaṭa{Q:b}',
        "and so will his wife, the carrier of firewood,"),
    Ayah('فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ',
        'fī jīdihā ḥa{Q:b}lu{Dg:m-m}i{Dg:m-m}asa{Q:d}',
        "with a rope of palm fibre around her neck."),
  ]),
  Surah(112, 'Al-Ikhlāṣ', 'الإخلاص', 'Sincerity', [
    Ayah('قُلْ هُوَ اللَّهُ أَحَدٌ', 'qul huwal-lāhu aḥa{Q:d}',
        "Say, “He is Allah, the One,"),
    Ayah('اللَّهُ الصَّمَدُ', 'allāhuṣ-ṣama{Q:d}',
        "Allah, on whom all depend, who depends on none."),
    Ayah('لَمْ يَلِدْ وَلَمْ يُولَدْ', 'lam yali{Q:d} wa lam yūla{Q:d}',
        "He does not beget, nor was He begotten,"),
    Ayah('وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
        'wa lam yaku{Dn:l-l}ahū kufuwan aḥa{Q:d}',
        "and there is nothing comparable to Him.”"),
  ]),
  Surah(113, 'Al-Falaq', 'الفلق', 'Daybreak', [
    Ayah('قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ', 'qul aʿūdhu birabbil-fala{Q:q}',
        "Say, “I seek refuge in the Lord of daybreak"),
    Ayah('مِن شَرِّ مَا خَلَقَ', 'mi{I:n} sharri mā khala{Q:q}',
        "from the evil of what He has created,"),
    Ayah('وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ',
        'wa mi{I:n} sharri ghāsiqin idhā waqa{Q:b}',
        "from the evil of the darkness when it settles,"),
    Ayah('وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ',
        'wa mi{I:n} sharri{G:n-n}affāthāti fil-ʿuqa{Q:d}',
        "from the evil of those who blow on knots,"),
    Ayah('وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
        'wa mi{I:n} sharri ḥāsidin idhā ḥasa{Q:d}',
        "and from the evil of the envious when they envy.”"),
  ]),
  Surah(114, 'An-Nās', 'الناس', 'People', [
    Ayah('قُلْ أَعُوذُ بِرَبِّ النَّاسِ', 'qul aʿūdhu birabbi{G:n-n}{Ma:ā}s',
        "Say, “I seek refuge in the Lord of people,"),
    Ayah('مَلِكِ النَّاسِ', 'maliki{G:n-n}{Ma:ā}s', "the King of people,"),
    Ayah('إِلَٰهِ النَّاسِ', 'ilāhi{G:n-n}{Ma:ā}s', "the God of people,"),
    Ayah('مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ',
        'mi{I:n} sharril-waswāsil-kha{G:nn}{Ma:ā}s',
        "from the evil of the whisperer who slinks away,"),
    Ayah('الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ',
        'alladhī yuwaswisu fī ṣudūri{G:n-n}{Ma:ā}s',
        "who whispers into the hearts of people,"),
    Ayah('مِنَ الْجِنَّةِ وَالنَّاسِ', 'minal-ji{G:nn}ati wa{G:n-n}{Ma:ā}s',
        "from among jinn and people.”"),
  ]),
];

Surah? surahByNumber(int n) {
  for (final s in kSurahs) {
    if (s.number == n) return s;
  }
  return null;
}
